apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-helm
spec:
  destination:
    namespace: LICENSEPLATE-test
    server: https://kubernetes.default.svc
  project: LICENSEPLATE

  sources:
    - chart: mysql
      repoURL: https://ymian.github.io/helm-mysql
      targetRevision: 1.0.0   # pick a version from the repo index
      helm:
        valueFiles:
          - $values/mysql-helm/values.yaml

    - ref: values
      repoURL: https://github.com/bcgov-c/tenant-gitops-LICENSEPLATE.git
      targetRevision: main

