apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-helm
spec:
  destination:
    namespace: LICENSEPLATE-test
    server: https://kubernetes.default.svc
  project: LICENSEPLATE
  sources:
    # Chart homepage:
    #   https://artifacthub.io/packages/helm/cloudpirates-mariadb/mariadb
    - chart: cloudpirates/mariadb
      repoURL: artifacts.developer.gov.bc.ca/helm-oci-virtual
      # For available versions, see "Chart Versions" on the chart's homepage or:
      #   https://artifacthub.io/api/v1/packages/helm/cloudpirates-mariadb/mariadb/feed/rss
      targetRevision: 0.13.2
      helm:
        valueFiles:
          - $values/mariadb-helm/values.yaml
    - ref: values
      repoURL: https://github.com/bcgov-c/tenant-gitops-LICENSEPLATE.git
      targetRevision: main

