apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mongodb-ephemeral-82
  annotations:
    description: "MongoDB 8.2 database service, with ephemeral storage."
    tags: "database,mongodb"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${MONGODB_NAME}
      labels:
        app: ${MONGODB_APP_LABEL}
    stringData:
      root-username: ${MONGODB_ROOT_USER}
      root-password: ${MONGODB_ROOT_PASSWORD}
      app-username: ${MONGODB_APP_USER}
      app-password: ${MONGODB_APP_PASSWORD}
      database-name: ${MONGODB_DATABASE}

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${MONGODB_NAME}
      labels:
        app: ${MONGODB_APP_LABEL}
    spec:
      ports:
        - port: 27017
          protocol: TCP
          targetPort: 27017
      selector:
        name: ${MONGODB_NAME}

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${MONGODB_NAME}
      labels:
        app: ${MONGODB_APP_LABEL}
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ${MONGODB_NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: ${MONGODB_NAME}
            app: ${MONGODB_APP_LABEL}
        spec:
          containers:
            - name: mongodb
              image: docker.io/library/mongo:8.2
              ports:
                - containerPort: 27017
                  protocol: TCP
              env:
                - name: MONGO_INITDB_ROOT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${MONGODB_NAME}
                      key: root-username
                - name: MONGO_INITDB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${MONGODB_NAME}
                      key: root-password
                - name: MONGO_INITDB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${MONGODB_NAME}
                      key: database-name
              readinessProbe:
                exec:
                  command:
                    - mongosh
                    - --eval
                    - db.adminCommand('ping')
                initialDelaySeconds: 5
                timeoutSeconds: 5
                periodSeconds: 10
              livenessProbe:
                tcpSocket:
                  port: 27017
                initialDelaySeconds: 30
                timeoutSeconds: 1
              volumeMounts:
                - name: mongodb-data
                  mountPath: /data/db
          volumes:
            - name: mongodb-data
              emptyDir: {}
parameters:
  - name: MONGODB_ROOT_USER
    displayName: MongoDB Root User
    description: Username for the MongoDB root user created at initialization.
    value: rootuser
    required: true
  - name: MONGODB_ROOT_PASSWORD
    displayName: MongoDB Root Password
    description: Password for the MongoDB root user created at initialization.
    value: rootpassword
    required: true
  - name: MONGODB_APP_USER
    displayName: MongoDB Rocket.Chat User
    description: Username for the Rocket.Chat application user (created manually).
    value: rocketchat
    required: true
  - name: MONGODB_APP_PASSWORD
    displayName: MongoDB Rocket.Chat User Password
    description: Password for the Rocket.Chat application user (created manually).
    value: rocketchatpass
    required: true
  - name: MONGODB_DATABASE
    displayName: MongoDB Database Name
    description: Name of the MongoDB database accessed by Rocket.Chat.
    value: rocketchat
    required: true
  - name: MONGODB_NAME
    displayName: MongoDB Service Name
    description: The name for the OpenShift Service/Secret/Deployment for this instance.
    value: mongodb-[username]
    required: true
  - name: MONGODB_APP_LABEL
    displayName: Application Label
    description: The label to use for the app.
    value: rocketchat-[username]
    required: true
