apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mongodb-ephemeral-82
  annotations:
    description: "MongoDB 8.2 database service, with ephemeral storage."
    tags: "database,mongodb"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${MONGODB_NAME}
      labels:
        app: ${MONGODB_APP_LABEL}
    stringData:
      database-user: ${MONGODB_USER}
      database-password: ${MONGODB_PASSWORD}
      database-admin-password: ${MONGODB_ADMIN_PASSWORD}
      database-name: ${MONGODB_DATABASE}
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${MONGODB_NAME}
      labels:
        app: ${MONGODB_APP_LABEL}
        name: ${MONGODB_NAME}
    spec:
      ports:
        - port: 27017
          protocol: TCP
          targetPort: 27017
      selector:
        name: ${MONGODB_NAME}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ${MONGODB_NAME}
      labels:
        app: ${MONGODB_APP_LABEL}
        name: ${MONGODB_NAME}
    spec:
      replicas: 1
      selector:
        matchLabels:
          name: ${MONGODB_NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: ${MONGODB_NAME}
            app: ${MONGODB_APP_LABEL}
        spec:
          containers:
            - name: mongodb
              image: docker.io/library/mongo:8.2
              ports:
                - containerPort: 27017
                  protocol: TCP
              env:
                - name: MONGO_INITDB_ROOT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: ${MONGODB_NAME}
                      key: database-user
                - name: MONGO_INITDB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${MONGODB_NAME}
                      key: database-admin-password
                - name: MONGO_INITDB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: ${MONGODB_NAME}
                      key: database-name
              readinessProbe:
                exec:
                  command:
                    - mongosh
                    - --eval
                    - db.adminCommand('ping')
                initialDelaySeconds: 5
                timeoutSeconds: 5
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                tcpSocket:
                  port: 27017
                initialDelaySeconds: 30
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              volumeMounts:
                - name: mongodb-data
                  mountPath: /data/db
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                limits:
                  cpu: 500m
                  memory: 1Gi
          volumes:
            - name: mongodb-data
              emptyDir: {}
parameters:
  - name: MONGODB_USER
    displayName: MongoDB Connection Username
    description: Username for MongoDB user that will be used for accessing the database.
    value: dbuser
    required: true
  - name: MONGODB_PASSWORD
    displayName: MongoDB Connection Password
    description: Password for the MongoDB connection user.
    value: dbpass
    required: true
  - name: MONGODB_ADMIN_PASSWORD
    displayName: MongoDB Admin Password
    description: Password for the MongoDB admin user.
    value: admindbpass
    required: true
  - name: MONGODB_DATABASE
    displayName: MongoDB Database Name
    description: Name of the MongoDB database accessed.
    value: rocketchat
    required: true
  - name: MONGODB_NAME
    displayName: MongoDB Service Name
    description: The name of the OpenShift Service exposed for this instance.
    value: mongodb
    required: true
  - name: MONGODB_APP_LABEL
    displayName: Application Label
    description: The label to use for the app.
    value: rocketchat
    required: true
